// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using datahub.Entity_Framework;

#nullable disable

namespace datahub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("domain.Models.AuthModel", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "expires");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "value");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.HasIndex("Value");

                    b.ToTable("Auths");

                    b.HasAnnotation("Relational:JsonPropertyName", "auths");
                });

            modelBuilder.Entity("domain.Models.Chat.ChatModel", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "chat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChatId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "candidate_id");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "candidate_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<int>("EmployerId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "employer_id");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "employer_name");

                    b.HasKey("ChatId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("EmployerId");

                    b.ToTable("Chats");

                    b.HasAnnotation("Relational:JsonPropertyName", "chat");
                });

            modelBuilder.Entity("domain.Models.Chat.MessageModel", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "candidate_id");

                    b.Property<int>("ChatId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "chat_id");

                    b.Property<int>("EmployerId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "employer_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "message");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "sent_at");

                    b.HasKey("MessageId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ChatId");

                    b.HasIndex("EmployerId");

                    b.ToTable("Messages");

                    b.HasAnnotation("Relational:JsonPropertyName", "sent_messages_as_candidate");
                });

            modelBuilder.Entity("domain.Models.CompanyModel", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "company_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "company_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("Github")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "github");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "linkedin");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "location");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "country");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "phone_number");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "register_date");

                    b.Property<string>("Telegram")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "telegram");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.Property<string>("WebSite")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "website");

                    b.HasKey("CompanyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasAnnotation("Relational:JsonPropertyName", "company");
                });

            modelBuilder.Entity("domain.Models.EducationModel", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "education_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EducationId"));

                    b.Property<DateTime>("DateOfEnrollment")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "date_of_enrollment");

                    b.Property<DateTime?>("DateOfGraduation")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "date_of_graduation");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "institution");

                    b.Property<bool>("IsPresentTime")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "is_present_time");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "level");

                    b.Property<int>("ResumeId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "resume_id");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "specialty");

                    b.HasKey("EducationId");

                    b.HasIndex("ResumeId");

                    b.ToTable("Educations");

                    b.HasAnnotation("Relational:JsonPropertyName", "educations");
                });

            modelBuilder.Entity("domain.Models.ExperienceModel", b =>
                {
                    b.Property<int>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "experience_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExperienceId"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "company");

                    b.Property<string>("Duties")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "duties");

                    b.Property<DateTime?>("EndOfWork")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "end_of_work");

                    b.Property<bool>("IsPresentTime")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "is_present_time");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "location");

                    b.Property<int>("ResumeId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "resume_id");

                    b.Property<string>("SpecialityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "speciality_name");

                    b.Property<DateTime>("StartOfWork")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "start_of_work");

                    b.Property<string>("WebSite")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "website");

                    b.HasKey("ExperienceId");

                    b.HasIndex("ResumeId");

                    b.ToTable("Experience");

                    b.HasAnnotation("Relational:JsonPropertyName", "experiences");
                });

            modelBuilder.Entity("domain.Models.FavoriteResumeModel", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "favorite_resume_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FavoriteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<int>("ResumeId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "resume_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.HasKey("FavoriteId");

                    b.HasIndex("ResumeId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteResumes");

                    b.HasAnnotation("Relational:JsonPropertyName", "favorite_resumes");
                });

            modelBuilder.Entity("domain.Models.FavoriteVacancyModel", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "favorite_vacancy_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FavoriteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.Property<int>("VacancyId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "vacancy_id");

                    b.HasKey("FavoriteId");

                    b.HasIndex("UserId");

                    b.HasIndex("VacancyId");

                    b.ToTable("FavoriteVacancies");

                    b.HasAnnotation("Relational:JsonPropertyName", "favorites");
                });

            modelBuilder.Entity("domain.Models.LanguageModel", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "language_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "language");

                    b.Property<int>("LanguageLevel")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "language_level");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.HasKey("LanguageId");

                    b.HasIndex("UserId");

                    b.ToTable("Languages");

                    b.HasAnnotation("Relational:JsonPropertyName", "languages");
                });

            modelBuilder.Entity("domain.Models.RecoveryModel", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "expires");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "is_used");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "value");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.HasIndex("Value");

                    b.ToTable("Recoveries");

                    b.HasAnnotation("Relational:JsonPropertyName", "recoveries");
                });

            modelBuilder.Entity("domain.Models.ResponseModel", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "response_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResponseId"));

                    b.Property<int?>("Reason")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "reason");

                    b.Property<string>("ReasonDescription")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "reason_description");

                    b.Property<DateTime>("ResponseOfDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "response_of_date");

                    b.Property<int>("ResumeId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "resume_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<int>("VacancyId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "vacancy_id");

                    b.HasKey("ResponseId");

                    b.HasIndex("ResumeId");

                    b.HasIndex("VacancyId");

                    b.ToTable("Responses");

                    b.HasAnnotation("Relational:JsonPropertyName", "responses");
                });

            modelBuilder.Entity("domain.Models.ResumeModel", b =>
                {
                    b.Property<int>("ResumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "resume_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResumeId"));

                    b.Property<string>("About")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "about");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "citizenship");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<DateTime>("DateOfBirthday")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "date_of_birthday");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<int>("Employment")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "employment");

                    b.Property<string>("Github")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "github");

                    b.Property<string>("ImageKey")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "image_key");

                    b.Property<bool>("IsMale")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "is_male");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "linkedin");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "location");

                    b.Property<int>("MaxSalary")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "max_salary");

                    b.Property<int>("MinSalary")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "min_salary");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "phone_number");

                    b.Property<string>("ResumeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "resume_name");

                    b.Property<string[]>("Skills")
                        .HasColumnType("text[]")
                        .HasAnnotation("Relational:JsonPropertyName", "skills");

                    b.Property<string>("SpecialityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "speciality_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("Telegram")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "telegram");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.Property<string>("WebSite")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "website");

                    b.Property<string>("WorkPermit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "work_permit");

                    b.Property<int>("WorkSchedule")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "work_schedule");

                    b.HasKey("ResumeId");

                    b.HasIndex("UserId");

                    b.ToTable("Resumes");

                    b.HasAnnotation("Relational:JsonPropertyName", "resumes");
                });

            modelBuilder.Entity("domain.Models.ReviewModel", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "review_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<int>("DurationOfWork")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "duration_of_work");

                    b.Property<int>("GrowthOpportunitiesGrade")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "growth_opportunities_grade");

                    b.Property<int>("HiringProcessGrade")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "hiring_process_grade");

                    b.Property<bool>("IsRecomended")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "is_recommended");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "job_title");

                    b.Property<int>("ManagementGrade")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "management_grade");

                    b.Property<int>("RestConditionsGrade")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "rest_conditions_grade");

                    b.Property<int>("SalaryGrade")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "salary_grade");

                    b.Property<int>("TeamGrade")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "team_grade");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.Property<int>("WorkConditionsGrade")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "work_conditions_grade");

                    b.Property<int>("WorkPlaceGrade")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "work_place_grade");

                    b.HasKey("ReviewId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasAnnotation("Relational:JsonPropertyName", "reviews");
                });

            modelBuilder.Entity("domain.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "first_name");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "is_blocked");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "patronymic");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email");

                    b.ToTable("Users");

                    b.HasAnnotation("Relational:JsonPropertyName", "user");
                });

            modelBuilder.Entity("domain.Models.VacancyModel", b =>
                {
                    b.Property<int>("VacancyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "vacancy_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VacancyId"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "about");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<int>("EducationLevel")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "education_level");

                    b.Property<int>("Employment")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "employment");

                    b.Property<int>("Experience")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "experience");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "is_opened");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "location");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "country");

                    b.Property<int>("MaxSalary")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "max_salary");

                    b.Property<int>("MinSalary")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "min_salary");

                    b.Property<string>("VacancyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "vacancy_name");

                    b.Property<int>("WorkSchedule")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "work_schedule");

                    b.HasKey("VacancyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Vacancies");

                    b.HasAnnotation("Relational:JsonPropertyName", "vacancy");
                });

            modelBuilder.Entity("domain.Models.AuthModel", b =>
                {
                    b.HasOne("domain.Models.UserModel", "User")
                        .WithMany("Auths")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("domain.Models.Chat.ChatModel", b =>
                {
                    b.HasOne("domain.Models.ResumeModel", "CandidateUser")
                        .WithMany("CandidateChats")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Models.CompanyModel", "EmployerUser")
                        .WithMany("EmployerChats")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateUser");

                    b.Navigation("EmployerUser");
                });

            modelBuilder.Entity("domain.Models.Chat.MessageModel", b =>
                {
                    b.HasOne("domain.Models.ResumeModel", "Candidate")
                        .WithMany("SentMessagesAsCandidate")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Models.Chat.ChatModel", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Models.CompanyModel", "Employer")
                        .WithMany("SentMessagesAsEmployer")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Chat");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("domain.Models.CompanyModel", b =>
                {
                    b.HasOne("domain.Models.UserModel", "User")
                        .WithOne("Company")
                        .HasForeignKey("domain.Models.CompanyModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("domain.Models.EducationModel", b =>
                {
                    b.HasOne("domain.Models.ResumeModel", "Resume")
                        .WithMany("Educations")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("domain.Models.ExperienceModel", b =>
                {
                    b.HasOne("domain.Models.ResumeModel", "Resume")
                        .WithMany("Experiences")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("domain.Models.FavoriteResumeModel", b =>
                {
                    b.HasOne("domain.Models.ResumeModel", "Resume")
                        .WithMany("Favorites")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Models.UserModel", "User")
                        .WithMany("FavoriteResumes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");

                    b.Navigation("User");
                });

            modelBuilder.Entity("domain.Models.FavoriteVacancyModel", b =>
                {
                    b.HasOne("domain.Models.UserModel", "User")
                        .WithMany("FavoriteVacancies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Models.VacancyModel", "Vacancy")
                        .WithMany("Favorites")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("domain.Models.LanguageModel", b =>
                {
                    b.HasOne("domain.Models.UserModel", "User")
                        .WithMany("Languages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("domain.Models.RecoveryModel", b =>
                {
                    b.HasOne("domain.Models.UserModel", "User")
                        .WithMany("Recoveries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("domain.Models.ResponseModel", b =>
                {
                    b.HasOne("domain.Models.ResumeModel", "Resume")
                        .WithMany("Responses")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Models.VacancyModel", "Vacancy")
                        .WithMany("Responses")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("domain.Models.ResumeModel", b =>
                {
                    b.HasOne("domain.Models.UserModel", "User")
                        .WithMany("Resumes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("domain.Models.ReviewModel", b =>
                {
                    b.HasOne("domain.Models.CompanyModel", "Company")
                        .WithMany("Reviews")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Models.UserModel", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("domain.Models.VacancyModel", b =>
                {
                    b.HasOne("domain.Models.CompanyModel", "Company")
                        .WithMany("Vacancies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("domain.Models.Chat.ChatModel", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("domain.Models.CompanyModel", b =>
                {
                    b.Navigation("EmployerChats");

                    b.Navigation("Reviews");

                    b.Navigation("SentMessagesAsEmployer");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("domain.Models.ResumeModel", b =>
                {
                    b.Navigation("CandidateChats");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("Favorites");

                    b.Navigation("Responses");

                    b.Navigation("SentMessagesAsCandidate");
                });

            modelBuilder.Entity("domain.Models.UserModel", b =>
                {
                    b.Navigation("Auths");

                    b.Navigation("Company");

                    b.Navigation("FavoriteResumes");

                    b.Navigation("FavoriteVacancies");

                    b.Navigation("Languages");

                    b.Navigation("Recoveries");

                    b.Navigation("Resumes");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("domain.Models.VacancyModel", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
