name: .NET Build and Test

on:
  push:
    branches:
      - master
      - ci-cd
  pull_request:
    branches:
      - master
      - ci-cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.*'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: |
        for test_project in $(find . -name "*.csproj" -path "*tests*"); do
          echo "Running tests in $test_project"
          dotnet test $test_project --no-build --verbosity normal
        done
